import * as THREE from 'three';
import audioClips from './audio.json';
import geometryTargets from './geometry.json';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
const stage=document.querySelector('#stage'),status=document.querySelector('#state'),message=document.querySelector('#message'),buttons=[document.querySelector('#yes'),document.querySelector('#no')];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x080b10,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;stage.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','Live 3D morphing Bit');renderer.domElement.setAttribute('role','img');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,50);camera.position.set(0,.1,5.6);camera.lookAt(0,0,0);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.05).texture;room.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xb3d9ff,0x152030,1.0));const key=new THREE.DirectionalLight(0xe5f5ff,2.7);key.position.set(-3,4,4);scene.add(key);const rim=new THREE.DirectionalLight(0x518cff,2.8);rim.position.set(2,1,-3);scene.add(rim);
const targets=geometryTargets.map(a=>new THREE.Float32BufferAttribute(a,3)),base=new THREE.BufferGeometry();base.setAttribute('position',targets[0].clone());base.morphAttributes.position=targets;base.computeVertexNormals();
const material=new THREE.MeshPhysicalMaterial({color:0xc1e6ff,metalness:.65,roughness:.27,clearcoat:1,clearcoatRoughness:.16,flatShading:true,emissive:0x12273e,emissiveIntensity:.28});const mesh=new THREE.Mesh(base,material);scene.add(mesh);mesh.rotation.set(.2,.25,.12);
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=128;shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d'),gradient=ctx.createRadialGradient(64,64,2,64,64,62);gradient.addColorStop(0,'rgba(102,182,255,0.24)');gradient.addColorStop(1,'rgba(102,182,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(3.3,3.3),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false,opacity:.42}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-1.85;scene.add(shadow);
const neutral=new THREE.Color(0xa9d7f3),gold=new THREE.Color(0xffb800),red=new THREE.Color(0xff341b),weights=[1,0,0,0],startWeights=[...weights];let mode='neutral',transitionAt=0,returnAt=0,audioTimer,returnTimer,frame=0,last=0,elapsed=0;const sounds={yes:new Audio(audioClips.yes),no:new Audio(audioClips.no)};Object.values(sounds).forEach(a=>{a.preload='auto';a.volume=.85;a.hidden=true;document.body.append(a)});
function setStatus(m){status.dataset.mode=m;status.textContent=m==='yes'?'Yes':m==='no'?'No':'Neutral';for(const b of buttons)b.setAttribute('aria-pressed',String(b.id===m));renderer.domElement.setAttribute('aria-label',m==='yes'?'Golden octahedron saying yes':m==='no'?'Red stellated polyhedron saying no':'Pale blue polyhedron shifting in neutral')}
function speak(m){clearTimeout(audioTimer);for(const a of Object.values(sounds)){a.pause();a.currentTime=0}const a=sounds[m];a.play().catch(error=>{if(error.name==='AbortError'||mode!==m)return;status.textContent=(m==='yes'?'Yes':'No')+' · audio unavailable'})}
function activate(m){clearTimeout(returnTimer);mode=m;transitionAt=elapsed;startWeights.splice(0,4,...weights);setStatus(m);if(m!=='neutral'){speak(m);returnTimer=setTimeout(()=>activate('neutral'),1450)}}
buttons.forEach(b=>{b.disabled=false;b.addEventListener('click',()=>activate(b.id))});document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key.toLowerCase()==='y')activate('yes');if(e.key.toLowerCase()==='n')activate('no')});
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();message.hidden=true;setStatus('neutral');
function tick(now){frame=requestAnimationFrame(tick);if(document.hidden){last=now;return}const dt=Math.min((now-(last||now))/1000,.05);last=now;elapsed+=dt;const q=Math.min(1,(elapsed-transitionAt)/(reduced?.16:(mode==='neutral'?.62:.30))),ease=q*q*q*(q*(q*6-15)+10);const n=reduced?0:(Math.sin(elapsed*3.6)+1)/2,targetW=mode==='yes'?[0,0,1,0]:mode==='no'?[0,0,0,1]:[1-n,n,0,0];for(let i=0;i<4;i++){weights[i]=THREE.MathUtils.lerp(startWeights[i],targetW[i],ease);mesh.morphTargetInfluences[i]=weights[i]}
material.color.copy(neutral).multiplyScalar(weights[0]+weights[1]).add(gold.clone().multiplyScalar(weights[2])).add(red.clone().multiplyScalar(weights[3]));material.emissive.copy(material.color).multiplyScalar(.12);if(!reduced){mesh.rotation.y+=dt*.22;mesh.rotation.x=.12+Math.sin(elapsed*.32)*.14;mesh.position.y=Math.sin(elapsed*1.15)*.075;mesh.rotation.z=.08+Math.sin(elapsed*.4)*.04}renderer.render(scene,camera)}tick(0);
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);clearTimeout(returnTimer);Object.values(sounds).forEach(a=>a.pause());message.hidden=false;message.textContent='The 3D view paused. Refresh this page to reconnect.';buttons.forEach(b=>b.disabled=true)});
}catch(error){message.hidden=false;message.innerHTML='This browser could not start the 3D view.<br>Try Chrome, Safari, or Firefox with hardware acceleration enabled.';status.textContent='3D unavailable';console.error(error)}
